modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT"
issueTrackerURL = "https://github.com/TheLMiffy1111/PackagedMekemicals/issues"

[[mods]]
	modId = "packagedmekemicals"
	version = "0@VERSION@"
	displayName = "PackagedMekemicals"
	description = "A PackagedAuto addon that adds Mekanism chemical support."
	logoFile = "packagedmekemicals.logo.png"
	authors = "TheLMiffy1111"
	displayURL = "https://www.curseforge.com/minecraft/mc-mods/packagedmekemicals"

[[dependencies.packagedmekemicals]]
	modId = "forge"
	versionRange = "[40,)"
	mandatory = true

[[dependencies.packagedmekemicals]]
	modId = "packagedauto"
	versionRange = "[3.1.4,)"
	mandatory = true

[[dependencies.packagedmekemicals]]
	modId = "mekanism"
	versionRange = "[10.2.3,)"
	mandatory = true
