modLoader = "javafml"
loaderVersion = "[2,)"
license = "MIT"
issueTrackerURL = "https://github.com/TheLMiffy1111/PackagedMekemicals/issues"

[[mods]]
	modId = "packagedmekemicals"
	version = "0@VERSION@"
	displayName = "PackagedMekemicals"
	description = "A PackagedAuto addon that adds Mekanism chemical support."
	logoFile = "packagedmekemicals.logo.png"
	authors = "TheLMiffy1111"
	displayURL = "https://www.curseforge.com/minecraft/mc-mods/packagedmekemicals"

[[dependencies.packagedauto]]
	modId = "neoforge"
	versionRange = "[20.4,)"
	type = "required"

[[dependencies.packagedmekemicals]]
	modId = "packagedauto"
	versionRange = "[4,)"
	type = "required"

[[dependencies.packagedmekemicals]]
	modId = "mekanism"
	versionRange = "[10.5,)"
	type = "required"
