modLoader="javafml"
loaderVersion="[44,)"
license="MIT"
issueTrackerURL="https://github.com/TheLMiffy1111/PackagedMekemicals/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/packagedmekemicals"
authors="TheLMiffy1111"
[[mods]]
modId="packagedmekemicals"
version="${file.jarVersion}"
displayName="PackagedMekemicals"
description="A PackagedAuto addon that adds Mekanism chemical support."

[[dependencies.packagedmekemicals]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.packagedmekemicals]]
    modId="packagedauto"
    mandatory=true
    versionRange="[3.4,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.packagedmekemicals]]
    modId="mekanism"
    mandatory=true
    versionRange="[10.4,)"
    ordering="NONE"
    side="BOTH"
